// <auto-generated />
using System;
using AplicaçãoSupport.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicaçãoSupport.Migrations
{
    [DbContext(typeof(AplicaçãoSupportDbContext))]
    partial class AplicaçãoSupportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AplicaçãoSupport.Models.AtendenteModel", b =>
                {
                    b.Property<int>("Atendente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Atendente_Id"));

                    b.Property<string>("Nome_Atendente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.HasKey("Atendente_Id");

                    b.ToTable("Atendente");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.AtendimentosModel", b =>
                {
                    b.Property<int>("Atendimento_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Atendimento_Id"));

                    b.Property<int>("AtendenteId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Atendimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inclusão")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Atendimento_Id");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.ClienteModel", b =>
                {
                    b.Property<int?>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("ClienteId"));

                    b.Property<int?>("EmpresaModelEmpresa_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Empresa_id")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Cliente")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EmpresaModelEmpresa_Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.EmpresaModel", b =>
                {
                    b.Property<int>("Empresa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Empresa_Id"));

                    b.Property<string>("Nome_Empresa")
                        .HasColumnType("longtext");

                    b.HasKey("Empresa_Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.AtendimentosModel", b =>
                {
                    b.HasOne("AplicaçãoSupport.Models.AtendenteModel", "Atendente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("AtendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicaçãoSupport.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Atendente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.ClienteModel", b =>
                {
                    b.HasOne("AplicaçãoSupport.Models.EmpresaModel", null)
                        .WithMany("clientes")
                        .HasForeignKey("EmpresaModelEmpresa_Id");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.AtendenteModel", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("AplicaçãoSupport.Models.EmpresaModel", b =>
                {
                    b.Navigation("clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
